export const HERO_QUOTE_ATTRIBUTION = "Izaro Phrecius probably";

export const HERO_QUOTES: string[] = [
  "A stacked deck is merely ambition with better odds.",
  "Only the unworthy call it gambling. An emperor calls it prophecy.",
  "In Wraeclast, every card is a trial, and every click a sentence.",
  "A deck unopened is cowardice with inventory space.",
  "The Goddess weighs your fortune in one hand, and your restraint in the other.",
  "To turn the card is to confess belief in destiny.",
  "An exile may count the odds. An emperor opens the deck.",
  "The empire was not built on prudence, aspirant. Open the deck.",
  "Every deck promises ascension. Most deliver disappointment.",
  "A worthy exile fears not the empty deck, but the one still unopened.",
  "Let Wraeclast judge your greed one card at a time.",
  "Prophecy, profit, ruin; all are dealt from the same deck.",
  "The stack is a tribunal: many sentences, few pardons.",
  "In Wraeclast, disappointment is common currency; glory is the rare drop.",
  "Each card may crown you, aspirant. Most merely remind you of your station.",
  "Fortune is a stern mistress; she takes often, and pays only when witnessed.",
  "The wise expect nothing. The worthy click again.",
  "A thousand dull prophecies make one divine verdict taste all the sweeter.",
  "To gamble is to purchase regret, with a chance at majesty.",
  "The deck promises treasure. It more often delivers character.",
  "Wraeclast does not deny your dreams. It simply invoices them first.",
  "Most cards are lessons. A rare few are coronations.",
  "Hope enters as a deck. It leaves as vendor trash, until it does not.",
  "An emperor accepts disappointment as tribute to the jackpot.",
  "The card that ruins you is common. The card that redeems you is patient.",
  "Open enough failures, aspirant, and fortune may mistake you for faithful.",
];
