/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StackedDecksRouteImport } from './routes/stacked-decks'
import { Route as SoothsayerRouteImport } from './routes/soothsayer'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as AttributionsRouteImport } from './routes/attributions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CardsIndexRouteImport } from './routes/cards/index'
import { Route as CardsCardIdRouteImport } from './routes/cards/$cardId'

const StackedDecksRoute = StackedDecksRouteImport.update({
  id: '/stacked-decks',
  path: '/stacked-decks',
  getParentRoute: () => rootRouteImport,
} as any)
const SoothsayerRoute = SoothsayerRouteImport.update({
  id: '/soothsayer',
  path: '/soothsayer',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const AttributionsRoute = AttributionsRouteImport.update({
  id: '/attributions',
  path: '/attributions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsIndexRoute = CardsIndexRouteImport.update({
  id: '/cards/',
  path: '/cards/',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsCardIdRoute = CardsCardIdRouteImport.update({
  id: '/cards/$cardId',
  path: '/cards/$cardId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attributions': typeof AttributionsRoute
  '/downloads': typeof DownloadsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/soothsayer': typeof SoothsayerRoute
  '/stacked-decks': typeof StackedDecksRoute
  '/cards/$cardId': typeof CardsCardIdRoute
  '/cards/': typeof CardsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attributions': typeof AttributionsRoute
  '/downloads': typeof DownloadsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/soothsayer': typeof SoothsayerRoute
  '/stacked-decks': typeof StackedDecksRoute
  '/cards/$cardId': typeof CardsCardIdRoute
  '/cards': typeof CardsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attributions': typeof AttributionsRoute
  '/downloads': typeof DownloadsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/soothsayer': typeof SoothsayerRoute
  '/stacked-decks': typeof StackedDecksRoute
  '/cards/$cardId': typeof CardsCardIdRoute
  '/cards/': typeof CardsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attributions'
    | '/downloads'
    | '/privacy-policy'
    | '/soothsayer'
    | '/stacked-decks'
    | '/cards/$cardId'
    | '/cards/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attributions'
    | '/downloads'
    | '/privacy-policy'
    | '/soothsayer'
    | '/stacked-decks'
    | '/cards/$cardId'
    | '/cards'
  id:
    | '__root__'
    | '/'
    | '/attributions'
    | '/downloads'
    | '/privacy-policy'
    | '/soothsayer'
    | '/stacked-decks'
    | '/cards/$cardId'
    | '/cards/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttributionsRoute: typeof AttributionsRoute
  DownloadsRoute: typeof DownloadsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SoothsayerRoute: typeof SoothsayerRoute
  StackedDecksRoute: typeof StackedDecksRoute
  CardsCardIdRoute: typeof CardsCardIdRoute
  CardsIndexRoute: typeof CardsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stacked-decks': {
      id: '/stacked-decks'
      path: '/stacked-decks'
      fullPath: '/stacked-decks'
      preLoaderRoute: typeof StackedDecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soothsayer': {
      id: '/soothsayer'
      path: '/soothsayer'
      fullPath: '/soothsayer'
      preLoaderRoute: typeof SoothsayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attributions': {
      id: '/attributions'
      path: '/attributions'
      fullPath: '/attributions'
      preLoaderRoute: typeof AttributionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards/': {
      id: '/cards/'
      path: '/cards'
      fullPath: '/cards/'
      preLoaderRoute: typeof CardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards/$cardId': {
      id: '/cards/$cardId'
      path: '/cards/$cardId'
      fullPath: '/cards/$cardId'
      preLoaderRoute: typeof CardsCardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttributionsRoute: AttributionsRoute,
  DownloadsRoute: DownloadsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SoothsayerRoute: SoothsayerRoute,
  StackedDecksRoute: StackedDecksRoute,
  CardsCardIdRoute: CardsCardIdRoute,
  CardsIndexRoute: CardsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
